language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build  -t shahrooz33ce/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shahrooz33ce/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-373732370451"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"