language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build  -t shahrooz33ce/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shahrooz33ce/docker-react npm run test